name: hello_flutter_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  #  https://pub.dev/packages/async
  async: ^2.2.0
  # https://pub.dev/packages/grpc
  grpc: ^4.0.1
  # https://pub.dev/packages/protobuf
  protobuf: ^5.0.0
  # https://pub.dev/packages/collection
  collection: ^1.17.1
  #
  # https://pub.dev/packages/uuid
  uuid: ^4.5.2
  # https://pub.dev/packages/fixnum
  fixnum: ^1.1.0
  # https://pub.dev/packages/geolocator
  geolocator: ^14.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
